[package]
name = "openclaw-tauri"
version = "1.1.7"
description = "OpenClaw desktop client powered by Tauri"
authors = ["OpenClaw"]
edition = "2021"

[lib]
name = "openclaw_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.10.1"

